#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

createPic()
{
    gnuplot<<EOF
    set terminal png size 800,700 font "Times-Roman,24"
    set output "result.png"
    set key bottom right
    set ylabel "T"
    set xlabel "x"
    set xrange [0:1]
    set grid
    set style circle radius graph 0.006
    plot 'toCompare/data.txt' title "analytical" with circles linewidth 2, 'postProcessing/singleGraph/0.002/line_T.xy' title "computation" with lines linewidth 2    
EOF
}



runApplication postProcess -func singleGraph

#gnuplot res-gnuplot 
createPic



#------------------------------------------------------------------------------
